-- Tedarikçi listesine göre MALİYET düzeltmesi (2026-08-27). Yalnız cost sütunu; satış fiyatına DOKUNULMAZ.
BEGIN;
UPDATE product_prices pr SET cost = 800, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a7' AND coalesce(pr.dim_key,'') = '1000';  -- Broşür [1CA7] 750 -> 800
UPDATE product_prices pr SET cost = 1100, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a7' AND coalesce(pr.dim_key,'') = '2000';  -- Broşür [2CA7] 1000 -> 1100
UPDATE product_prices pr SET cost = 1950, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a7' AND coalesce(pr.dim_key,'') = '5000';  -- Broşür [5CA7] 1900 -> 1950
UPDATE product_prices pr SET cost = 3700, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a7' AND coalesce(pr.dim_key,'') = '10000';  -- Broşür [10CA7] 3650 -> 3700
UPDATE product_prices pr SET cost = 900, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '1000';  -- Broşür [1CA5] 850 -> 900
UPDATE product_prices pr SET cost = 1200, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '2000';  -- Broşür [2CA5] 1150 -> 1200
UPDATE product_prices pr SET cost = 2100, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '5000';  -- Broşür [5CA5] 2150 -> 2100
UPDATE product_prices pr SET cost = 1600, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '1000';  -- Broşür [1CA4] 1500 -> 1600
UPDATE product_prices pr SET cost = 2200, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '2000';  -- Broşür [2CA4] 2100 -> 2200
UPDATE product_prices pr SET cost = 3950, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '5000';  -- Broşür [5CA4] 4000 -> 3950
UPDATE product_prices pr SET cost = 7600, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '10000';  -- Broşür [10CA4] 7500 -> 7600
UPDATE product_prices pr SET cost = 3100, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a3' AND coalesce(pr.dim_key,'') = '1000';  -- Broşür [1CA3] 3000 -> 3100
UPDATE product_prices pr SET cost = 4300, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a3' AND coalesce(pr.dim_key,'') = '2000';  -- Broşür [2CA3] 4100 -> 4300
UPDATE product_prices pr SET cost = 14900, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'brosur' AND coalesce(pr.option_key,'') = 'a3' AND coalesce(pr.dim_key,'') = '10000';  -- Broşür [10CA3] 14600 -> 14900
UPDATE product_prices pr SET cost = 1000, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'pro-brosur' AND coalesce(pr.option_key,'') = 'a7' AND coalesce(pr.dim_key,'') = '1000';  -- Pro Broşür [PRO1A7] 950 -> 1000
UPDATE product_prices pr SET cost = 1100, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'pro-brosur' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '1000';  -- Pro Broşür [PRO1A5] 1050 -> 1100
UPDATE product_prices pr SET cost = 1450, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'pro-brosur' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '2000';  -- Pro Broşür [PRO2A5] 1400 -> 1450
UPDATE product_prices pr SET cost = 1950, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'pro-brosur' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '1000';  -- Pro Broşür [PRO1A4] 2000 -> 1950
UPDATE product_prices pr SET cost = 3300, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a7' AND coalesce(pr.dim_key,'') = '3000';  -- Selefonlu Broşür [CBS1] 3250 -> 3300
UPDATE product_prices pr SET cost = 6300, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a7' AND coalesce(pr.dim_key,'') = '6000';  -- Selefonlu Broşür [CBS2] 6250 -> 6300
UPDATE product_prices pr SET cost = 12300, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a7' AND coalesce(pr.dim_key,'') = '12000';  -- Selefonlu Broşür [CBS3] 12000 -> 12300
UPDATE product_prices pr SET cost = 3200, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '2000';  -- Selefonlu Broşür [CBS4] 3100 -> 3200
UPDATE product_prices pr SET cost = 6200, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '4000';  -- Selefonlu Broşür [CBS5] 5900 -> 6200
UPDATE product_prices pr SET cost = 9200, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '6000';  -- Selefonlu Broşür [CBS6] 8800 -> 9200
UPDATE product_prices pr SET cost = 3100, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '1000';  -- Selefonlu Broşür [CBS7] 2900 -> 3100
UPDATE product_prices pr SET cost = 6000, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '2000';  -- Selefonlu Broşür [CBS8] 5600 -> 6000
UPDATE product_prices pr SET cost = 11500, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '4000';  -- Selefonlu Broşür [CBS9] 10000 -> 11500
UPDATE product_prices pr SET cost = 6000, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a3' AND coalesce(pr.dim_key,'') = '1000';  -- Selefonlu Broşür [CBS10] 5600 -> 6000
UPDATE product_prices pr SET cost = 11500, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a3' AND coalesce(pr.dim_key,'') = '2000';  -- Selefonlu Broşür [CBS11] 10000 -> 11500
UPDATE product_prices pr SET cost = 21000, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'selefonlu-brosur' AND coalesce(pr.option_key,'') = 'a3' AND coalesce(pr.dim_key,'') = '4000';  -- Selefonlu Broşür [CBS12] 18500 -> 21000
UPDATE product_prices pr SET cost = 1950, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'afis-105gr' AND coalesce(pr.option_key,'') = '34x49' AND coalesce(pr.dim_key,'') = '250';  -- Afişler [AF1] 1750 -> 1950
UPDATE product_prices pr SET cost = 3300, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'afis-105gr' AND coalesce(pr.option_key,'') = '49x69' AND coalesce(pr.dim_key,'') = '250';  -- Afişler [AF4] 2700 -> 3300
UPDATE product_prices pr SET cost = 2100, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'antetli-kagit' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '4000';  -- Antetli [ANT1] 1800 -> 2100
UPDATE product_prices pr SET cost = 4000, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'antetli-kagit' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '8000';  -- Antetli [ANT2] 3500 -> 4000
UPDATE product_prices pr SET cost = 5850, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'antetli-kagit' AND coalesce(pr.option_key,'') = 'a5' AND coalesce(pr.dim_key,'') = '12000';  -- Antetli [ANT3] 5000 -> 5850
UPDATE product_prices pr SET cost = 2000, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'antetli-kagit' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '2000';  -- Antetli [ANT4] 1700 -> 2000
UPDATE product_prices pr SET cost = 3700, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'antetli-kagit' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '4000';  -- Antetli [ANT5] 3300 -> 3700
UPDATE product_prices pr SET cost = 5400, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'antetli-kagit' AND coalesce(pr.option_key,'') = 'a4' AND coalesce(pr.dim_key,'') = '6000';  -- Antetli [ANT6] 4850 -> 5400
UPDATE product_prices pr SET cost = 650, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'magnet-promosyon' AND coalesce(pr.option_key,'') = 'oval' AND coalesce(pr.dim_key,'') = '1000';  -- Magnet [MAG2] 630 -> 650
UPDATE product_prices pr SET cost = 2800, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'kapi-aski-brosur' AND coalesce(pr.option_key,'') = 'ask1' AND coalesce(pr.dim_key,'') = '1000';  -- KAPI ASKI BROŞÜRLERİ [ASK1] 2625 -> 2800
UPDATE product_prices pr SET cost = 3000, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'kapi-aski-brosur' AND coalesce(pr.option_key,'') = 'ask2' AND coalesce(pr.dim_key,'') = '1000';  -- KAPI ASKI BROŞÜRLERİ [ASK2] 2875 -> 3000
UPDATE product_prices pr SET cost = 4850, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'kapi-aski-brosur' AND coalesce(pr.option_key,'') = 'ask3' AND coalesce(pr.dim_key,'') = '1000';  -- KAPI ASKI BROŞÜRLERİ [ASK3] 4700 -> 4850

-- Kartvizit (kod birebir eslesiyor; tedarikci listesi YALNIZ 1000 adet kademesini fiyatliyor)
UPDATE product_prices pr SET cost = 260, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'mna' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [MNA] 1000 adet
UPDATE product_prices pr SET cost = 320, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'cyp' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [CYP] 1000 adet
UPDATE product_prices pr SET cost = 310, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'cym' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [CYM] 1000 adet
UPDATE product_prices pr SET cost = 320, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'kl' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [KL] 1000 adet
UPDATE product_prices pr SET cost = 430, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'o-cok' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [O-COK] 1000 adet
UPDATE product_prices pr SET cost = 650, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'o-sek' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [O-SEK] 1000 adet
UPDATE product_prices pr SET cost = 600, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'eko-sek' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [EKO-SEK] 1000 adet
UPDATE product_prices pr SET cost = 750, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 's-sek' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [S-SEK] 1000 adet
UPDATE product_prices pr SET cost = 1000, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'a-sek' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [A-SEK] 1000 adet
UPDATE product_prices pr SET cost = 715, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'tank' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [TANK] 1000 adet
UPDATE product_prices pr SET cost = 600, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'ay' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [AY] 1000 adet
UPDATE product_prices pr SET cost = 620, updated_at = now() FROM products p WHERE pr.product_id = p.id AND p.slug = 'klasik-kartvizit' AND coalesce(pr.option_key,'') = 'gy' AND coalesce(pr.dim_key,'') = '1000';  -- Kartvizit [GY] 1000 adet
COMMIT;

-- Kontrol
SELECT p.slug, pr.option_key, pr.dim_key, pr.cost FROM product_prices pr JOIN products p ON pr.product_id=p.id WHERE p.slug IN ('brosur','pro-brosur','selefonlu-brosur','afis-105gr','antetli-kagit','magnet-promosyon','kapi-aski-brosur') ORDER BY p.slug, pr.option_key, pr.dim_key;
